### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/Self-Service#15]
For `Writing Help Online - 12521 - WHO 1000 - 1A`
it errors:

``` javascript
TypeError: Cannot read property '1' of null
    at Request._callback (/Users/glavin/Documents/Project Dev/UniCal/node_modules/self-service-banner/lib/getCoursesSchedule.js:147:23)
    at Request.self.callback (/Users/glavin/Documents/Project Dev/UniCal/node_modules/self-service-banner/node_modules/request/request.js:123:22)
    at Request.EventEmitter.emit (events.js:98:17)
    at Request.<anonymous> (/Users/glavin/Documents/Project Dev/UniCal/node_modules/self-service-banner/node_modules/request/request.js:893:14)
    at Request.EventEmitter.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/glavin/Documents/Project Dev/UniCal/node_modules/self-service-banner/node_modules/request/request.js:844:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:920:16
    at process._tickCallback (node.js:415:13)
```

Changing the regex solves the problem.

Before: `/(.*) - ([0-9]*) - (.{4}) ([0-9]{4}) - (.*)/`
After: `/(.*) - ([0-9]*) - (.*) ([0-9]{4}) - (.*)/`

**Comment by Glavin001** [comment]
- [x] Unit Test verifying bug, and should be passing when bug fixed:

```
$ mocha tests -g 'WHO'

  Writing Help Online - 12521 - WHO 1000 - 1A
error
․

  0 passing (393ms)
  1 failing

  1) User #Unsecured API should list all courses for subject with short identifier (WHO):
     Uncaught TypeError: Cannot read property '1' of null
      at Request._callback (/Users/glavin/Documents/Project Dev/Self-Service/lib/getCoursesSchedule.js:147:23)
      at Request.self.callback (/Users/glavin/Documents/Project Dev/Self-Service/node_modules/request/request.js:123:22)
      at Request.EventEmitter.emit (events.js:98:17)
      at Request.<anonymous> (/Users/glavin/Documents/Project Dev/Self-Service/node_modules/request/request.js:893:14)
      at Request.EventEmitter.emit (events.js:117:20)
      at IncomingMessage.<anonymous> (/Users/glavin/Documents/Project Dev/Self-Service/node_modules/request/request.js:844:12)
      at IncomingMessage.EventEmitter.emit (events.js:117:20)
      at _stream_readable.js:920:16
      at process._tickCallback (node.js:415:13)
```
